//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutors.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeRanges
    {
        public int AgeRangeID { get; set; }
        public string AgeRange { get; set; }
    }
}
