//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutors.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Duration { get; set; }
        public int TutorID { get; set; }
        public Nullable<int> AgeRangeID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
